// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var EventRe = require("./EventRe.js");

function Impl() {
  return /* module */[];
}

var include = EventRe.Impl(/* module */[]);

var eventPhase = include[0];

exports.Impl = Impl;
exports.eventPhase = eventPhase;
/* include Not a pure module */
