// Generated by BUCKLESCRIPT VERSION 1.4.3 , PLEASE EDIT WITH CARE
'use strict';


new Date();

new Date(0);

new Date(0, 1);

new Date(0, 1, 2);

new Date(0, 1, 2, 3);

new Date(0, 1, 2, 3, 4);

new Date(0, 1, 2, 3, 4, 5);

Date.utc();

Date.utc(0, 1);

Date.utc(0, 1, 2);

Date.utc(0, 1, 2, 3);

Date.utc(0, 1, 2, 3, 4);

Date.utc(0, 1, 2, 3, 4, 5);

Date.now();

var date = new Date("Dec 25, 1995");

date.getDate();

date.getDay();

date.getFullYear();

date.getHours();

date.getMilliseconds();

date.getMinutes();

date.getMonth();

date.getSeconds();

date.getTime();

date.getTimezoneOffset();

date.getUTCDate();

date.getUTCDay();

date.getUTCFullYear();

date.getUTCHours();

date.getUTCMilliseconds();

date.getUTCMinutes();

date.getUTCMonth();

date.getUTCSeconds();

date.getYear();

date.setDate(0);

date.setFullYear(0);

date.setFullYear(0, 1);

date.setFullYear(0, 1, 2);

date.setHours(0);

date.setHours(0, 1);

date.setHours(0, 1, 2);

date.setHours(0, 1, 2, 3);

date.setMilliseconds(0);

date.setMinutes(0);

date.setMinutes(0, 1);

date.setMinutes(0, 1, 2);

date.setMonth(0);

date.setMonth(0, 1);

date.setSeconds(0);

date.setSeconds(0, 1);

date.setTime(0);

date.setUTCDate(0);

date.setUTCFullYear(0);

date.setUTCFullYear(0, 1);

date.setUTCFullYear(0, 1, 2);

date.setUTCHours(0);

date.setUTCHours(0, 1);

date.setUTCHours(0, 1, 2);

date.setUTCHours(0, 1, 2, 3);

date.setUTCMilliseconds(0);

date.setUTCMinutes(0);

date.setUTCMinutes(0, 1);

date.setUTCMinutes(0, 1, 2);

date.setUTCMonth(0);

date.setUTCMonth(0, 1);

date.setUTCSeconds(0);

date.setUTCSeconds(0, 1);

date.setUTCTime(0);

date.toDateString();

date.toGMTString();

date.toISOString();

date.toJSON();

date.toLocaleDateString();

date.toLocaleString();

date.toLocaleTimeString();

date.toString();

date.toTimeString();

date.toUTCString();

date.valueOf();

setInterval(function () {
      console.log("hello!");
      return /* () */0;
    }, 1000);

window.innerWidth;

window.innerHeight;

document.getElementById("foo").value;

window.addEventListener("click", function () {
      console.log("asd");
      return /* () */0;
    });

window.onload = function () {
  console.log("load");
  return /* () */0;
};

var p = fetch("/greatings");

var p2 = p.then(function (res) {
        return res.text();
      }).then(function (text) {
      console.log(text);
      return /* () */0;
    });

p2.catch(function (err) {
      console.log(err);
      return /* () */0;
    });

p.then(function (res) {
        return res.json();
      }).then(function (json) {
      console.log(json);
      return /* () */0;
    });

/*  Not a pure module */
