// Generated by BUCKLESCRIPT VERSION 1.4.3, PLEASE EDIT WITH CARE
'use strict';


setInterval(function () {
      console.log("hello!");
      return /* () */0;
    }, 1000);

/*  Not a pure module */
