'use strict';


var _DEPTH_BUFFER_BIT = 256;

var _STENCIL_BUFFER_BIT = 1024;

var _COLOR_BUFFER_BIT = 16384;

var _POINTS = 0;

var _LINES = 1;

var _LINE_LOOP = 2;

var _LINE_STRIP = 3;

var _TRIANGLES = 4;

var _TRIANGLE_STRIP = 5;

var _TRIANGLE_FAN = 6;

var _CULL_FACE = 2884;

var _BLEND = 3042;

var _DITHER = 3024;

var _STENCIL_TEST = 2960;

var _DEPTH_TEST = 2929;

var _SCISSOR_TEST = 3089;

var _POLYGON_OFFSET_FILL = 32823;

var _SAMPLE_ALPHA_TO_COVERAGE = 32926;

var _SAMPLE_COVERAGE = 32928;

var _ZERO = 0;

var _ONE = 1;

var _SRC_COLOR = 768;

var _ONE_MINUS_SRC_COLOR = 769;

var _SRC_ALPHA = 770;

var _ONE_MINUS_SRC_ALPHA = 771;

var _DST_ALPHA = 772;

var _ONE_MINUS_DST_ALPHA = 773;

var _BYTE = 5120;

var _UNSIGNED_BYTE = 5121;

var _SHORT = 5122;

var _UNSIGNED_SHORT = 5123;

var _INT = 5124;

var _UNSIGNED_INT = 5125;

var _FLOAT = 5126;

var _FRONT = 1028;

var _BACK = 1029;

var _FRONT_AND_BACK = 1032;

var _FRAGMENT_SHADER = 35632;

var _VERTEX_SHADER = 35633;

var _ARRAY_BUFFER = 34962;

var _ELEMENT_ARRAY_BUFFER = 34963;

var _ARRAY_BUFFER_BINDING = 34964;

var _ELEMENT_ARRAY_BUFFER_BINDING = 34965;

var _STREAM_DRAW = 35040;

var _STATIC_DRAW = 35044;

var _DYNAMIC_DRAW = 35048;

exports._DEPTH_BUFFER_BIT = _DEPTH_BUFFER_BIT;
exports._STENCIL_BUFFER_BIT = _STENCIL_BUFFER_BIT;
exports._COLOR_BUFFER_BIT = _COLOR_BUFFER_BIT;
exports._POINTS = _POINTS;
exports._LINES = _LINES;
exports._LINE_LOOP = _LINE_LOOP;
exports._LINE_STRIP = _LINE_STRIP;
exports._TRIANGLES = _TRIANGLES;
exports._TRIANGLE_STRIP = _TRIANGLE_STRIP;
exports._TRIANGLE_FAN = _TRIANGLE_FAN;
exports._CULL_FACE = _CULL_FACE;
exports._BLEND = _BLEND;
exports._DITHER = _DITHER;
exports._STENCIL_TEST = _STENCIL_TEST;
exports._DEPTH_TEST = _DEPTH_TEST;
exports._SCISSOR_TEST = _SCISSOR_TEST;
exports._POLYGON_OFFSET_FILL = _POLYGON_OFFSET_FILL;
exports._SAMPLE_ALPHA_TO_COVERAGE = _SAMPLE_ALPHA_TO_COVERAGE;
exports._SAMPLE_COVERAGE = _SAMPLE_COVERAGE;
exports._ZERO = _ZERO;
exports._ONE = _ONE;
exports._SRC_COLOR = _SRC_COLOR;
exports._ONE_MINUS_SRC_COLOR = _ONE_MINUS_SRC_COLOR;
exports._SRC_ALPHA = _SRC_ALPHA;
exports._ONE_MINUS_SRC_ALPHA = _ONE_MINUS_SRC_ALPHA;
exports._DST_ALPHA = _DST_ALPHA;
exports._ONE_MINUS_DST_ALPHA = _ONE_MINUS_DST_ALPHA;
exports._BYTE = _BYTE;
exports._UNSIGNED_BYTE = _UNSIGNED_BYTE;
exports._SHORT = _SHORT;
exports._UNSIGNED_SHORT = _UNSIGNED_SHORT;
exports._INT = _INT;
exports._UNSIGNED_INT = _UNSIGNED_INT;
exports._FLOAT = _FLOAT;
exports._FRONT = _FRONT;
exports._BACK = _BACK;
exports._FRONT_AND_BACK = _FRONT_AND_BACK;
exports._FRAGMENT_SHADER = _FRAGMENT_SHADER;
exports._VERTEX_SHADER = _VERTEX_SHADER;
exports._ARRAY_BUFFER = _ARRAY_BUFFER;
exports._ELEMENT_ARRAY_BUFFER = _ELEMENT_ARRAY_BUFFER;
exports._ARRAY_BUFFER_BINDING = _ARRAY_BUFFER_BINDING;
exports._ELEMENT_ARRAY_BUFFER_BINDING = _ELEMENT_ARRAY_BUFFER_BINDING;
exports._STREAM_DRAW = _STREAM_DRAW;
exports._STATIC_DRAW = _STATIC_DRAW;
exports._DYNAMIC_DRAW = _DYNAMIC_DRAW;
/* No side effect */
