// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';


var CanvasElement = /* module */[];

var Canvas2d = 0;

var WebGl = 0;

exports.Canvas2d = Canvas2d;
exports.WebGl = WebGl;
exports.CanvasElement = CanvasElement;
/* No side effect */
