// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Js_boolean = require("bs-platform/lib/js/js_boolean.js");

function setScrollRestoration(self, value) {
  self.scrollRestoration = Js_boolean.to_js_boolean(value);
  return /* () */0;
}

exports.setScrollRestoration = setScrollRestoration;
/* No side effect */
