// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var EventTargetRe = require("../events/EventTargetRe.js");

function Impl() {
  return /* module */[];
}

EventTargetRe.Impl(/* module */[]);

exports.Impl = Impl;
/*  Not a pure module */
