// Generated by BUCKLESCRIPT VERSION 1.4.3 , PLEASE EDIT WITH CARE
'use strict';

var Document   = require("../../src/dom/document");
var NodeFilter = require("../../src/dom/nodeFilter");

var el = document.createElement("strong");

document.characterSet;

document.compatMode;

document.docType;

document.documentElement;

document.documentURI;

Document.hidden(document);

document.implementation;

document.lastStyleSheetSet;

Document.pointerLockElement(document);

document.preferredStyleSheetSet;

Document.scrollingElement(document);

document.selectedStyleSheetSet;

document.selectedStyleSheetSet = "muh-stylesheet";

document.styleSheets;

document.styleSheetSets;

document.visibilityState;

document.adoptNode(el);

document.createAttribute("data-foo");

document.createAttributeNS("http://...", "foo");

document.createComment("witty comment");

document.createDocumentFragment();

document.createElement("div");

document.createElement("div", ({}));

document.createElementNS("http://...", "foo");

document.createEementNS("http://...", "div", ({}));

document.createEvent("MyCustomEvent");

document.createNodeIterator(el);

document.createNodeIterator(el, 0);

document.createNodeIterator(el, 0, NodeFilter.make(function () {
          return 0;
        }));

document.elementFromPoint(0, 0);

document.elementsFromPoint(0, 0);

document.enableStyleSheetsForSet("my-stylesheet-set");

document.exitPointerLock();

document.getAnimations();

document.getElementsByClassName("lstlisting");

document.getElementsByTagName("code");

document.getElementsByTagNameNS("http://...", "foo");

document.importNode(el);

Document.importNodeDeep(el, document);

Document.getElementById("root", document);

Document.querySelector(".lstlisting", document);

document.querySelectorAll(".lstlisting");

exports.el = el;
/* el Not a pure module */
