// Generated by BUCKLESCRIPT VERSION 1.4.3 , PLEASE EDIT WITH CARE
'use strict';

var Document   = require("../../src/dom/document");
var NodeFilter = require("../../src/dom/nodeFilter");

var el = document.createElement("strong");

document.characterSet;

document.compatMode;

document.docType;

document.documentElement;

document.documentURI;

Document.hidden(document);

document.implementation;

document.lastStyleSheetSet;

Document.pointerLockElement(document);

document.preferredStyleSheetSet;

Document.scrollingElement(document);

document.selectedStyleSheetSet;

document.selectedStyleSheetSet = "muh-stylesheet";

document.styleSheets;

document.styleSheetSets;

document.visibilityState;

document.adoptNode(el);

document.createAttribute("data-foo");

document.createAttributeNS("http://...", "foo");

document.createComment("witty comment");

document.createDocumentFragment();

document.createElement("div");

document.createElement("div", ({}));

document.createElementNS("http://...", "foo");

document.createEementNS("http://...", "div", ({}));

document.createEvent("MyCustomEvent");

document.createNodeIterator(el);

document.createNodeIterator(el, 0);

document.createNodeIterator(el, 0, NodeFilter.make(function () {
          return 0;
        }));

document.elementFromPoint(0, 0);

document.elementsFromPoint(0, 0);

document.enableStyleSheetsForSet("my-stylesheet-set");

document.exitPointerLock();

document.getAnimations();

document.getElementsByClassName("lstlisting");

document.getElementsByTagName("code");

document.getElementsByTagNameNS("http://...", "foo");

document.importNode(el);

Document.importNodeDeep(el, document);

Document.getElementById("root", document);

Document.querySelector(".lstlisting", document);

document.querySelectorAll(".lstlisting");

Document.activeElement(document);

Document.body(document);

document.body = el;

document.cookie;

document.cookie = "foo=bar;reason=ml";

document.defaultView;

document.designMode;

document.designMode = "on";

document.dir;

document.dir = "ltr";

Document.domain(document);

document.domain = "reason.ml";

document.embeds;

document.forms;

document.head;

document.images;

document.lastModified;

document.links;

document.location;

document.location = "http://reason.ml";

document.plugins;

document.readyState;

document.referrer;

document.scripts;

document.title;

document.title = "Reason: Rapid Expressive Systems Programming.";

document.URL;

document.close();

Document.execCommand("copy", /* false */0, /* None */0, document);

document.getElementsByName("angry-joe");

document.getSelection();

Document.hasFocus(document);

document.open();

Document.queryCommandEnabled("copy", document);

Document.queryCommandIndeterm("cut", document);

Document.queryCommandSupported("paste", document);

document.queryCommandValue("fontName");

document.write("Hello World!");

document.writeln("Hello Newline!");

exports.el = el;
/* el Not a pure module */
