// Generated by BUCKLESCRIPT VERSION 1.4.3 , PLEASE EDIT WITH CARE
'use strict';

var Element = require("../../src/dom/element");

var el = document.createElement("strong");

var el2 = document.createElement("small");

var $$event = document.createEvent("my-event");

el.assignedSlot;

el.attributes;

el.classList;

el.className;

el.className = "my-class-name";

el.clientHeight;

el.clientLeft;

el.clientTop;

el.clientWidth;

el.id;

el.id = "my-id";

el.innerHTML;

el.innerHTML = "<strong>stuff</strong>";

el.localName;

Element.namespaceURI(el);

Element.nextElementSibling(el);

el.outerHTML;

el.outerHTML = "<strong>stuff</strong>";

Element.prefix(el);

Element.previousElementSibling(el);

el.scrollHeight;

el.scrollLeft;

el.scrollLeft = 0;

el.scrollTop;

el.scrollTop = 0;

el.scrollWidth;

el.shadowRoot;

el.slot;

el.slot = "<strong>stuff</strong>";

el.tagName;

el.attachShadow({
      mode: "open"
    });

el.animate({
      transform: "translateT(0px)"
    }, {
      duration: 1000
    });

el.closest("input");

el.createShadowRoot();

Element.getAttribute("href", el);

Element.getAttributeNS("http://...", "foo", el);

el.getBoundingClientRect();

el.getClientRects();

el.getElementsByClassName("some-class-name");

el.getElementsByTagName("pre");

el.getElementsByTagNameNS("http://...", "td");

Element.hasAttribute("data-my-value", el);

Element.hasAttributeNS("http://...", "foo", el);

Element.hasAttributes(el);

Element.insertAdjacentElement("beforebegin", el2, el);

Element.insertAdjacentText("afterbegin", "text", el);

Element.matches("input", el);

Element.querySelector("input", el);

el.querySelectorAll("input");

el.releasePointerCapture($$event.pointerId);

el.remove();

el.removeAttribute("href");

el.removeAttributeNS("http://...", "foo");

el.requestFullscreen();

el.requestPointerLock();

el.scrollIntoView();

Element.scrollIntoViewNoAlignToTop(el);

el.scrollIntoView({
      block: "end",
      behvaior: "smooth"
    });

el.setAttribute("href", "http://...");

el.setAttributeNS("http://...", "foo", "bar");

el.setPointerCapture($$event.pointerId);

el.accessKey;

el.accessKey = "";

el.accessKeyLabel;

el.contentEditable;

el.contentEditable = "inherit";

Element.isContentEditable(el);

el.contextMenu;

el.contextMenu = el2;

el.dataset;

el.dir;

el.dir = "ltr";

Element.draggable(el);

Element.setDraggable(el, /* true */1);

el.dropzone;

Element.hidden(el);

Element.setHidden(el, /* true */1);

Element.itemScope(el);

Element.setItemScope(el, /* true */1);

el.itemType;

el.itemId;

el.itemId = "my-id";

el.itemRef;

el.itemProp;

el.itemValue;

el.itemValue = ({});

el.lang;

el.lang = "en";

el.offsetHeight;

el.offsetLeft;

el.offsetParent;

el.offsetTop;

el.offsetWidth;

Element.spellcheck(el);

Element.setSpellcheck(el, /* true */1);

el.style;

el.tabIndex;

el.tabIndex = 42;

el.title;

el.title = "hovertext!";

Element.translate(el);

Element.setTranslate(el, /* true */1);

el.blur();

el.click();

el.focus();

el.forceSpellCheck();

exports.el      = el;
exports.el2     = el2;
exports.$$event = $$event;
/* el Not a pure module */
