// Generated by BUCKLESCRIPT VERSION 1.4.3 , PLEASE EDIT WITH CARE
'use strict';

var Element = require("../../src/dom/element");

var el = document.createElement("strong");

var el2 = document.createElement("small");

var $$event = document.createEvent("my-event");

el.assignedSlot;

el.attributes;

el.classList;

el.className;

el.className = "my-class-name";

el.clientHeight;

el.clientLeft;

el.clientTop;

el.clientWidth;

el.id;

el.id = "my-id";

el.innerHTML;

el.innerHTML = "<strong>stuff</strong>";

el.localName;

Element.namespaceURI(el);

Element.nextElementSibling(el);

el.outerHTML;

el.outerHTML = "<strong>stuff</strong>";

Element.prefix(el);

Element.previousElementSibling(el);

el.scrollHeight;

el.scrollLeft;

el.scrollLeft = 0;

el.scrollTop;

el.scrollTop = 0;

el.scrollWidth;

el.shadowRoot;

el.slot;

el.slot = "<strong>stuff</strong>";

el.tagName;

el.attachShadow({
      mode: "open"
    });

el.animate({
      transform: "translateT(0px)"
    }, {
      duration: 1000
    });

el.closest("input");

el.createShadowRoot();

Element.getAttribute("href", el);

Element.getAttributeNS("http://...", "foo", el);

el.getBoundingClientRect();

el.getClientRects();

el.getElementsByClassName("some-class-name");

el.getElementsByTagName("pre");

el.getElementsByTagNameNS("http://...", "td");

Element.hasAttribute("data-my-value", el);

Element.hasAttributeNS("http://...", "foo", el);

Element.hasAttributes(el);

Element.insertAdjacentElement("beforebegin", el2, el);

Element.insertAdjacentText("afterbegin", "text", el);

Element.matches("input", el);

Element.querySelector("input", el);

el.querySelectorAll("input");

el.releasePointerCapture($$event.pointerId);

el.remove();

el.removeAttribute("href");

el.removeAttributeNS("http://...", "foo");

el.requestFullscreen();

el.requestPointerLock();

el.scrollIntoView();

Element.scrollIntoViewNoAlignToTop(el);

el.scrollIntoView({
      block: "end",
      behvaior: "smooth"
    });

el.setAttribute("href", "http://...");

el.setAttributeNS("http://...", "foo", "bar");

el.setPointerCapture($$event.pointerId);

exports.el      = el;
exports.el2     = el2;
exports.$$event = $$event;
/* el Not a pure module */
