open ReasonJs;

let el = document |> Document.createElement "strong";
let el2 = document |> Document.createElement "small";
let event = document |> Document.createEvent "my-event";

/* Node interface */
let node = Element.asNode el;
let node2 = Element.asNode el2;
let _ = Node.childNodes node;
let _ = Node.firstChild node;
let _ = Node.lastChild node;
let _ = Node.nextSibling node;
let _ = Node.nodeName node;
let _ = Node.nodeType node;
let _ = Node.nodeValue node;
let _ = Node.setNodeValue node Js.Null.empty;
let _ = Node.ownerDocument node;
let _ = Node.parentNode node;
let _ = Node.parentElement node;
let _ = Node.previousSibling node;
let _ = Node.rootNode node;
let _ = Node.textContent node;
let _ = Node.setTextContent node "foo";

let _ = Node.appendChild node2 node;
let _ = Node.cloneNode node;
let _ = Node.cloneNodeDeep (Js.Boolean.to_js_boolean true) node;
let _ = Node.compareDocumentPosition node2 node;
let _ = Node.contains node2 node;
let _ = Node.getRootNode node;
let _ = Node.getRootNodeComposed (Js.Boolean.to_js_boolean true) node;
let _ = Node.hasChildNodes node;
let _ = Node.insertBefore node2 Js.Null.empty node;
let _ = Node.isDefaultNamespace "http://..." node;
let _ = Node.isEqualNode node2 node;
let _ = Node.isSameNode node2 node;
let _ = Node.lookupPrefix node;
let _ = Node.lookupNamespaceURI Js.Null.empty node;
let _ = Node.normalize node;
let _ = Node.removeChild node2 node;

/* Element interface */
let _ = Element.assignedSlot el;
let _ = Element.attributes el;
let _ = Element.classList el;
let _ = Element.className el;
let _ = Element.setClassName el "my-class-name";
let _ = Element.clientHeight el;
let _ = Element.clientLeft el;
let _ = Element.clientTop el;
let _ = Element.clientWidth el;
let _ = Element.id el;
let _ = Element.setId el "my-id";
let _ = Element.innerHTML el;
let _ = Element.setInnerHTML el "<strong>stuff</strong>";
let _ = Element.localName el;
let _ = Element.namespaceURI el;
let _ = Element.nextElementSibling el;
let _ = Element.outerHTML el;
let _ = Element.setOuterHTML el "<strong>stuff</strong>";
let _ = Element.prefix el;
let _ = Element.previousElementSibling el;
let _ = Element.scrollHeight el;
let _ = Element.scrollLeft el;
let _ = Element.setScrollLeft el 0;
let _ = Element.scrollTop el;
let _ = Element.setScrollTop el 0;
let _ = Element.scrollWidth el;
let _ = Element.shadowRoot el;
let _ = Element.slot el;
let _ = Element.setSlot el "<strong>stuff</strong>";
let _ = Element.tagName el;

let _ = Element.attachShadow { "mode": "open" } el;
let _ = Element.animate { "transform": "translateT(0px)" } { "duration": 1000 } el;
let _ = Element.closest "input" el;
let _ = Element.createShadowRoot el;
let _ = Element.getAttribute "href" el;
let _ = Element.getAttributeNS "http://..." "foo" el;
let _ = Element.getBoundingClientRect el;
let _ = Element.getClientRects el;
let _ = Element.getElementsByClassName "some-class-name" el;
let _ = Element.getElementsByTagName "pre" el;
let _ = Element.getElementsByTagNameNS "http://..." "td" el;
let _ = Element.hasAttribute "data-my-value" el;
let _ = Element.hasAttributeNS "http://..." "foo" el;
let _ = Element.hasAttributes el;
let _ = Element.insertAdjacentElement "beforebegin" el2 el;
let _ = Element.insertAdjacentText "afterbegin" "text" el;
let _ = Element.matches "input" el;
let _ = Element.querySelector "input" el;
let _ = Element.querySelectorAll "input" el;
let _ = Element.releasePointerCapture (Event.pointerId event) el;
let _ = Element.remove el;
let _ = Element.removeAttribute "href" el;
let _ = Element.removeAttributeNS "http://..." "foo" el;
let _ = Element.requestFullscreen el;
let _ = Element.requestPointerLock el;
let _ = Element.scrollIntoView el;
let _ = Element.scrollIntoViewNoAlignToTop el;
let _ = Element.scrollIntoViewWithOptions { "block": "end", "behvaior": "smooth" } el;
let _ = Element.setAttribute "href" "http://..." el;
let _ = Element.setAttributeNS "http://..." "foo" "bar" el;
let _ = Element.setPointerCapture (Event.pointerId event) el;

/* HTMLElement interface */
let _ = Element.accessKey el;
let _ = Element.setAccessKey el "";
let _ = Element.accessKeyLabel el;
let _ = Element.contentEditable el;
let _ = Element.setContentEditable el "inherit";
let _ = Element.isContentEditable el;
let _ = Element.contextMenu el;
let _ = Element.setContextMenu el el2;
let _ = Element.dataset el;
let _ = Element.dir el;
let _ = Element.setDir el "ltr";
let _ = Element.draggable el;
let _ = Element.setDraggable el true;
let _ = Element.dropzone el;
let _ = Element.hidden el;
let _ = Element.setHidden el true;
let _ = Element.itemScope el;
let _ = Element.setItemScope el true;
let _ = Element.itemType el;
let _ = Element.itemId el;
let _ = Element.setItemId el "my-id";
let _ = Element.itemRef el;
let _ = Element.itemProp el;
let _ = Element.itemValue el;
let _ = Element.setItemValue el [%bs.raw "{}"];
let _ = Element.lang el;
let _ = Element.setLang el "en";
let _ = Element.offsetHeight el;
let _ = Element.offsetLeft el;
let _ = Element.offsetParent el;
let _ = Element.offsetTop el;
let _ = Element.offsetWidth el;
let _ = Element.spellcheck el;
let _ = Element.setSpellcheck el true;
let _ = Element.style el;
/* let _ = Element.setStyle el CSSStyleDeclaration.t; /* TODO: No way to make a CSSStyleDeclaration at the moment */*/
let _ = Element.tabIndex el;
let _ = Element.setTabIndex el 42;
let _ = Element.title el;
let _ = Element.setTitle el "hovertext!";
let _ = Element.translate el;
let _ = Element.setTranslate el true;

Element.blur el;
Element.click el;
Element.focus el;
Element.forceSpellCheck el;
