// Generated by BUCKLESCRIPT VERSION 1.4.3 , PLEASE EDIT WITH CARE
'use strict';

var EventTarget = require("../../src/dom/eventTarget");

var target = document.createElement("strong");

var $$event = new Event("my-event");

function handleClick() {
  console.log("asd");
  return /* () */0;
}

target.addEventListener("click", handleClick);

target.addEventListener("click", handleClick, {
      passive: /* true */1
    });

EventTarget.addEventListenerUseCapture("click", handleClick, target);

target.removeEventListener("click", handleClick);

target.removeEventListener("click", handleClick, {
      passive: /* true */1
    });

EventTarget.removeEventListenerUseCapture("click", handleClick, target);

target.dispatchEvent($$event);

exports.target      = target;
exports.$$event     = $$event;
exports.handleClick = handleClick;
/* target Not a pure module */
