// Generated by BUCKLESCRIPT VERSION 1.4.3 , PLEASE EDIT WITH CARE
'use strict';

var Document     = require("../../src/dom/document");
var TestHelpers  = require("../testHelpers");
var HtmlDocument = require("../../src/dom/htmlDocument");

var el = document.createElement("strong");

var htmlDocument = TestHelpers.unsafelyUnwrapOption(Document.asHtmlDocument(document));

HtmlDocument.activeElement(htmlDocument);

HtmlDocument.body(htmlDocument);

htmlDocument.body = el;

htmlDocument.cookie;

htmlDocument.cookie = "foo=bar;reason=ml";

htmlDocument.defaultView;

HtmlDocument.designMode(htmlDocument);

HtmlDocument.setDesignMode(htmlDocument, /* On */0);

HtmlDocument.dir(htmlDocument);

HtmlDocument.setDir(htmlDocument, /* Ltr */0);

HtmlDocument.domain(htmlDocument);

htmlDocument.domain = "reason.ml";

htmlDocument.embeds;

htmlDocument.forms;

htmlDocument.head;

htmlDocument.images;

htmlDocument.lastModified;

htmlDocument.links;

htmlDocument.location;

htmlDocument.location = "http://reason.ml";

htmlDocument.plugins;

HtmlDocument.readyState(htmlDocument);

htmlDocument.referrer;

htmlDocument.scripts;

htmlDocument.title;

htmlDocument.title = "Reason: Rapid Expressive Systems Programming.";

htmlDocument.URL;

htmlDocument.close();

HtmlDocument.execCommand("copy", /* false */0, /* None */0, htmlDocument);

htmlDocument.getElementsByName("angry-joe");

htmlDocument.getSelection();

HtmlDocument.hasFocus(htmlDocument);

htmlDocument.open();

HtmlDocument.queryCommandEnabled("copy", htmlDocument);

HtmlDocument.queryCommandIndeterm("cut", htmlDocument);

HtmlDocument.queryCommandSupported("paste", htmlDocument);

htmlDocument.queryCommandValue("fontName");

htmlDocument.write("Hello World!");

htmlDocument.writeln("Hello Newline!");

exports.el           = el;
exports.htmlDocument = htmlDocument;
/* el Not a pure module */
