// Generated by BUCKLESCRIPT VERSION 1.4.3 , PLEASE EDIT WITH CARE
'use strict';

var Element     = require("../../src/dom/element");
var HtmlElement = require("../../src/dom/htmlElement");
var TestHelpers = require("../testHelpers");

var el = TestHelpers.unsafelyUnwrapOption(Element.asHtmlElement(document.createElement("strong")));

var el2 = TestHelpers.unsafelyUnwrapOption(Element.asHtmlElement(document.createElement("small")));

var $$event = document.createEvent("my-event");

el.accessKey;

el.accessKey = "";

el.accessKeyLabel;

HtmlElement.contentEditable(el);

HtmlElement.setContentEditable(el, /* Inherit */2);

HtmlElement.isContentEditable(el);

el.contextMenu;

el.contextMenu = el2;

el.dataset;

HtmlElement.dir(el);

HtmlElement.setDir(el, /* Rtl */1);

HtmlElement.draggable(el);

HtmlElement.setDraggable(el, /* true */1);

el.dropzone;

HtmlElement.hidden(el);

HtmlElement.setHidden(el, /* true */1);

HtmlElement.itemScope(el);

HtmlElement.setItemScope(el, /* true */1);

el.itemType;

el.itemId;

el.itemId = "my-id";

el.itemRef;

el.itemProp;

el.itemValue;

el.itemValue = ({});

el.lang;

el.lang = "en";

el.offsetHeight;

el.offsetLeft;

el.offsetParent;

el.offsetTop;

el.offsetWidth;

HtmlElement.spellcheck(el);

HtmlElement.setSpellcheck(el, /* true */1);

el.style;

el.tabIndex;

el.tabIndex = 42;

el.title;

el.title = "hovertext!";

HtmlElement.translate(el);

HtmlElement.setTranslate(el, /* true */1);

el.blur();

el.click();

el.focus();

el.forceSpellCheck();

exports.el      = el;
exports.el2     = el2;
exports.$$event = $$event;
/* el Not a pure module */
