// Generated by BUCKLESCRIPT VERSION 1.4.3 , PLEASE EDIT WITH CARE
'use strict';

var Node = require("../../src/dom/node");

var node = document.createElement("strong");

var node2 = document.createElement("small");

node.childNodes;

Node.firstChild(node);

Node.lastChild(node);

Node.nextSibling(node);

node.nodeName;

Node.nodeType(node);

Node.nodeValue(node);

Node.setNodeValue(node, /* None */0);

node.ownerDocument;

Node.parentNode(node);

Node.parentElement(node);

Node.previousSibling(node);

node.rootNode;

node.textContent;

node.textContent = "foo";

node.appendChild(node2);

node.cloneNode();

Node.cloneNodeDeep(node);

node.compareDocumentPosition(node2);

Node.contains(node2, node);

node.getRootNode();

Node.getRootNodeComposed(node);

Node.hasChildNodes(node);

Node.insertBefore(node2, /* None */0, node);

Node.isDefaultNamespace("http://...", node);

Node.isEqualNode(node2, node);

Node.isSameNode(node2, node);

node.lookupPrefix();

node.normalize();

node.removeChild(node2);

exports.node  = node;
exports.node2 = node2;
/* node Not a pure module */
