// Generated by BUCKLESCRIPT VERSION 1.4.3 , PLEASE EDIT WITH CARE
'use strict';

var Selection = require("../../src/dom/selection");

var node = document.createElement("strong");

var sel = document.getSelection();

var range = new Range();

sel.anchorNode;

sel.anchorOffset;

sel.focusNode;

sel.focusOffset;

sel.isCollapsed;

sel.rangeCount;

sel.getRangeAt(0);

sel.collapse(node, 0);

sel.extend(node, 0);

sel.collapseToStart();

sel.collapseToEnd();

sel.selectAllChildren(node);

sel.addRange(range);

sel.removeRange(range);

sel.removeAllRanges();

sel.deleteFromDocument();

sel.toString();

Selection.containsNode(node, /* true */1, sel);

exports.node  = node;
exports.sel   = sel;
exports.range = range;
/* node Not a pure module */
