// Generated by BUCKLESCRIPT VERSION 1.4.3 , PLEASE EDIT WITH CARE
'use strict';

var Window = require("../../src/dom/window");

var el = document.createElement("strong");

var $$event = document.createEvent("my-event");

function handleClick() {
  console.log("asd");
  return /* () */0;
}

window.document;

Window.fullScreen(window);

window.history;

window.innerWidth;

window.innerHeight;

window.location;

window.location = "http://reason.ml";

window.parent;

window.top;

window.alert("hello!");

Window.confirm("is ok?", window);

window.getComputedStyle(el);

window.getComputedStyle(el, "hover");

window.prompt("type you password, please?");

window.prompt("type password or use this?", "password");

window.scroll(0, 0);

window.onload = function () {
  console.log("load");
  return /* () */0;
};

exports.el          = el;
exports.$$event     = $$event;
exports.handleClick = handleClick;
/* el Not a pure module */
